export ZSH="$HOME/.oh-my-zsh"

ZSH_THEME="carbonfox-steeef"

plugins=(git
        zsh-autosuggestions
        zsh-syntax-highlighting
        you-should-use
        zsh-vi-mode
)

source $ZSH/oh-my-zsh.sh

if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Path variables
export PATH="$PATH:/opt/nvim-linux64/bin"
export PATH="$PATH:$HOME/.local/bin"

# Function to create a directory and cd into the newly created directory
function mkcd {
  if [ ! -n "$1" ]; then
    echo "Enter a directory name"
  elif [ -d $1 ]; then
    echo "\`$1' already exists"
  else
    mkdir $1 && cd $1
  fi
}

# Replace ls with exa
alias ls="exa --icons"
alias ll="exa --icons -l"
alias la="exa --icons -a"
alias lla="exa --icons -la"
alias tree="exa --icons -T"

# Enable remote desktop
alias remotedesktop="sudo /etc/init.d/xrdp"

# Removing zone identifier files generated by Windows
alias rmzone="find . -name '*Zone.Identifier' -delete"

# Django manage alias
alias manage="python3 manage.py"

# Start OS232 VM and SSH to VM
alias os232="bash ~/start_os232.sh"

# Python environment alias
alias activate="source env/bin/activate"

# Script to extract and clean up zip file downloaded from SCeLe
alias extract_scele="python ~/.config/bin/extract_scele_zip.py"

# Smart man pages
alias fman="compgen -c | fzf | xargs tldr"

# Neovim
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Go version manager
[[ -s "/home/oka/.gvm/scripts/gvm" ]] && source "/home/oka/.gvm/scripts/gvm"

# Python version manager
export PYENV_ROOT="$HOME/.pyenv"
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# Fuzzy finder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS' 
--color=fg:#c0caf5,bg:#1a1b26,hl:#bb9af7
--color=fg+:#c0caf5,bg+:#1a1b26,hl+:#7dcfff
--color=info:#7aa2f7,prompt:#7dcfff,pointer:#7dcfff 
--color=marker:#9ece6a,spinner:#9ece6a,header:#9ece6a'

# Zoxide
eval "$(zoxide init zsh)"
