[colors.primary]
background = "#161616"
foreground = "#f2f4f8"
dim_foreground = "#b6b8bb"
bright_foreground = "#f9fbff"

[colors.cursor]
text = "#f2f4f8"
cursor = "#b6b8bb"

[colors.vi_mode_cursor]
text = "#f2f4f8"
cursor = "#33b1ff"

[colors.search.matches]
foreground = "#f2f4f8"
background = "#525253"

[colors.search.focused_match]
foreground = "#f2f4f8"
background = "#3ddbd9"

[colors.footer_bar]
foreground = "#f2f4f8"
background = "#353535"

[colors.hints.start]
foreground = "#f2f4f8"
background = "#3ddbd9"

[colors.hints.end]
foreground = "#f2f4f8"
background = "#353535"

[colors.selection]
text = "#f2f4f8"
background = "#2a2a2a"

[colors.normal]
black = "#282828"
red = "#ee5396"
green = "#25be6a"
yellow = "#08bdba"
blue = "#78a9ff"
magenta = "#be95ff"
cyan = "#33b1ff"
white = "#dfdfe0"

[colors.bright]
black = "#484848"
red = "#f16da6"
green = "#46c880"
yellow = "#2dc7c4"
blue = "#8cb6ff"
magenta = "#c8a5ff"
cyan = "#52bdff"
white = "#e4e4e5"

[colors.dim]
black = "#222222"
red = "#ca4780"
green = "#1fa25a"
yellow = "#07a19e"
blue = "#6690d9"
magenta = "#a27fd9"
cyan = "#2b96d9"
white = "#bebebe"

[[colors.indexed_colors]]
index = 16
color = "#3ddbd9"

[[colors.indexed_colors]]
index = 17
color = "#ff7eb6"

[shell]
program = 'C:\Windows\System32\wsl.exe'
args = ["--cd ~"]

[font]
normal = { family = "JetBrainsMono Nerd Font Mono" }
size = 12

[window]
padding = { x = 8, y = 8 }
startup_mode = "Maximized"
decorations = "none"

[mouse]
hide_when_typing = true

[keyboard]
bindings = [
    { key = "PageUp", mods = "Shift", mode = "~Alt", action = "ReceiveChar" },
    { key = "PageDown", mods = "Shift", mode = "~Alt", action = "ReceiveChar" },
    { key = "Home", mods = "Shift", mode = "~Alt", action = "ReceiveChar" },
    { key = "End", mods = "Shift", mode = "~Alt", action = "ReceiveChar" },
    { key = "K", mods = "Command", mode = "~Vi|~Search", action = "ReceiveChar" },
    { key = "F", mods = "Control|Shift", mode = "~Search", action = "ReceiveChar" },
    { key = "F", mods = "Command", mode = "~Search", action = "ReceiveChar" },
    { key = "B", mods = "Control|Shift", mode = "~Search", action = "ReceiveChar" },
    { key = "B", mods = "Command", mode = "~Search", action = "ReceiveChar" },
    { key = "Paste", action = "ReceiveChar" },
    { key = "Copy", action = "ReceiveChar" },
    { key = "V", mods = "Control|Shift", mode = "~Vi", action = "ReceiveChar" },
    { key = "V", mods = "Command", action = "ReceiveChar" },
    { key = "C", mods = "Control|Shift", action = "ReceiveChar" },
    { key = "C", mods = "Command", action = "ReceiveChar" },
    { key = "C", mods = "Control|Shift", mode = "Vi|~Search", action = "ReceiveChar" },
    { key = "C", mods = "Command", mode = "Vi|~Search", action = "ReceiveChar" },
    { key = "Insert", mods = "Shift", action = "ReceiveChar" },
    { key = "F11", action = "ToggleFullscreen" },
]
